"""Vertex write-back adapter.

Materialises generated artifacts as markdown files inside the connected
vertex repo clone, under ``<repo>/synthesis/<category>/<type-id>.md``.

Write-back is opt-in:

    project.metadata.vertex.write_enabled = true   # required
    project.metadata.vertex.write_subdir = "synthesis"  # optional, default

The adapter never touches files outside its own subfolder, so customer-
authored vertex content is safe. A small ``_index.md`` is maintained inside
the subfolder summarising the latest synthesis run.
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from pathlib import Path

from app.synthesis.categories import CATEGORY_LABELS
from app.synthesis.exporters.common import body_to_lines
from app.synthesis.models import Artifact
from app.synthesis.writers.base import WriteBackResult, WriteBackTarget
from app.utils.project_paths import resolve_project_repo_path

logger = logging.getLogger(__name__)

_DEFAULT_SUBDIR = "synthesis"


class VertexWriteBack(WriteBackTarget):
    target = "vertex"

    async def push(self, project: dict, artifacts: list[Artifact]) -> WriteBackResult:
        meta = project.get("metadata") or {}
        vertex_meta = meta.get("vertex") or {}
        enabled = bool(vertex_meta.get("write_enabled"))
        result = WriteBackResult(target=self.target, enabled=enabled)

        if not enabled:
            return result

        repo_path = project.get("repo_path") or ""
        if not repo_path:
            result.errors.append("project has no repo_path")
            return result

        try:
            root = resolve_project_repo_path(repo_path)
        except Exception as exc:
            logger.exception("vertex writeback: resolve failed")
            result.errors.append(f"resolve repo_path: {exc}")
            return result

        if not root.exists() or not root.is_dir():
            result.errors.append(f"repo not found: {root}")
            return result

        subdir = str(vertex_meta.get("write_subdir") or _DEFAULT_SUBDIR).strip("/\\")
        base = root / subdir
        try:
            base.mkdir(parents=True, exist_ok=True)
        except Exception as exc:
            result.errors.append(f"mkdir {base}: {exc}")
            return result

        for artifact in artifacts:
            path = self._artifact_path(base, artifact)
            try:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(self._render(artifact), encoding="utf-8")
                result.written.append(path.relative_to(root).as_posix())
            except Exception as exc:
                logger.warning("vertex writeback: %s -> %s failed", artifact.id, path)
                result.errors.append(f"{artifact.type_id}: {exc}")

        try:
            index_path = base / "_index.md"
            index_path.write_text(self._render_index(project, artifacts), encoding="utf-8")
            result.written.append(index_path.relative_to(root).as_posix())
        except Exception as exc:
            result.errors.append(f"_index.md: {exc}")

        return result

    @staticmethod
    def _artifact_path(base: Path, artifact: Artifact) -> Path:
        category = str(artifact.category)
        type_id = artifact.type_id or "artifact"
        return base / category / f"{type_id}.md"

    @staticmethod
    def _render(artifact: Artifact) -> str:
        lines: list[str] = []
        lines.append(f"# {artifact.title or artifact.type_id}")
        lines.append("")
        lines.append(
            f"_Category: **{CATEGORY_LABELS.get(artifact.category, artifact.category)}**_  "
        )
        lines.append(f"_Type: `{artifact.type_id}`_  ")
        lines.append(f"_Version: {artifact.version} · Status: {artifact.status}_  ")
        lines.append(f"_Generated: {artifact.updated_at.isoformat()}_")
        lines.append("")
        lines.append("> Auto-generated by CORE Framework synthesis. Edit upstream artifact, ")
        lines.append("> not this file — it is overwritten on every synthesize run.")
        lines.append("")

        if artifact.summary:
            lines.append("## Summary")
            lines.append("")
            lines.append(artifact.summary.strip())
            lines.append("")

        if artifact.body:
            lines.append("## Detail")
            lines.append("")
            for label, value in body_to_lines(artifact.body):
                if not value:
                    continue
                lines.append(f"### {label}")
                lines.append("")
                lines.append(value)
                lines.append("")

        if artifact.citations:
            lines.append("## Sources")
            lines.append("")
            for c in artifact.citations:
                quote = f" — {c.quote.strip()[:240]}" if c.quote else ""
                lines.append(f"- `{c.source_id}`{quote}")
            lines.append("")

        return "\n".join(lines).rstrip() + "\n"

    @staticmethod
    def _render_index(project: dict, artifacts: list[Artifact]) -> str:
        now = datetime.now(UTC).isoformat()
        name = str(project.get("name") or project.get("slug") or "Project")
        out: list[str] = []
        out.append(f"# Synthesis — {name}")
        out.append("")
        out.append(f"_Last run: {now}_  ")
        out.append(f"_Artifacts: {len(artifacts)}_")
        out.append("")
        out.append("| Category | Type | Title | Version |")
        out.append("| --- | --- | --- | --- |")
        for a in artifacts:
            cat_label = CATEGORY_LABELS.get(a.category, str(a.category))
            title = (a.title or a.type_id).replace("|", "\\|")
            out.append(f"| {cat_label} | `{a.type_id}` | {title} | {a.version} |")
        out.append("")
        out.append("> Generated by CORE Framework synthesis write-back. Files in this folder ")
        out.append("> are regenerated on every run; do not edit them directly.")
        return "\n".join(out) + "\n"
