#!/usr/bin/env node
/**
 * Regenerate JSON Schema + TypeScript-type artifacts for every
 * Pydantic schema registered in `backend/app/schemas/_export.py`.
 *
 * Pipeline:
 *   1. Spawn the backend Python to dump JSON Schema dicts to disk.
 *   2. For each kind, run json-schema-to-typescript via npx to
 *      produce a .d.ts.
 *   3. Emit an index `schemas.d.ts` re-exporting the per-kind types.
 *   4. Emit a `compatibility.json` summarising which kinds + which
 *      schema_version values are currently supported.
 *
 * Subprocess discipline: every shell-out uses execFileSync with
 * array arguments and shell:false. The script never builds a
 * command string with user-controlled fragments.
 */

import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = resolve(root, "packages/create-core-app/src/generated");
const pythonCmd = process.env.CORE_PYTHON ?? "uv";
const usingUv = pythonCmd === "uv";

mkdirSync(outDir, { recursive: true });

// Python one-shot: import the export registry, dump each schema as
// JSON to stdout in a structured envelope the JS side parses.
const dumpProgram = [
  "import json",
  "from app.schemas._constants import KNOWN_KINDS",
  "from app.schemas._export import SCHEMA_BY_KIND, assert_registry_matches_known_kinds, export_json_schema",
  "assert_registry_matches_known_kinds()",
  "out = {}",
  "for kind in sorted(KNOWN_KINDS):",
  "    out[kind] = {",
  "        'schema': export_json_schema(kind),",
  "        'schema_versions': [arg for arg in SCHEMA_BY_KIND[kind].model_fields['schema_version'].annotation.__args__],",
  "    }",
  "print(json.dumps(out))",
].join("\n");

console.log("[gen:schemas] dumping JSON Schemas from Pydantic...");
const dumpArgs = usingUv
  ? ["run", "python", "-c", dumpProgram]
  : ["-c", dumpProgram];
const dumpCwd = resolve(root, "backend");
const dumped = execFileSync(pythonCmd, dumpArgs, {
  cwd: dumpCwd,
  encoding: "utf8",
  stdio: ["ignore", "pipe", "inherit"],
});

let payload;
try {
  payload = JSON.parse(dumped.trim());
} catch (err) {
  console.error("[gen:schemas] failed to parse Python dump:", err.message);
  console.error("[gen:schemas] raw output:\n", dumped);
  process.exit(1);
}

const kinds = Object.keys(payload).sort();
for (const kind of kinds) {
  const schemaPath = resolve(outDir, `${kind}.schema.json`);
  writeFileSync(schemaPath, JSON.stringify(payload[kind].schema, null, 2) + "\n", "utf8");
  console.log(`[gen:schemas]   wrote ${schemaPath}`);
}

console.log("[gen:schemas] generating TypeScript types...");
for (const kind of kinds) {
  const schemaPath = resolve(outDir, `${kind}.schema.json`);
  const tsPath = resolve(outDir, `${kind}.d.ts`);
  // json-schema-to-typescript reads --input and writes --output;
  // no shell interpolation.
  execFileSync(
    "npx",
    ["--yes", "json-schema-to-typescript", "--input", schemaPath, "--output", tsPath, "--strictIndexSignatures"],
    { cwd: root, stdio: "inherit" },
  );
  console.log(`[gen:schemas]   wrote ${tsPath}`);
}

// Index re-export so the CLI can `import type { CoreDiscoveryMarker } from "./generated/schemas"`.
const indexLines = [
  "// Generated by scripts/gen-schemas.mjs — DO NOT EDIT BY HAND.",
  "",
];
for (const kind of kinds) {
  // Convert snake_case to PascalCase for the type name (matches what
  // json-schema-to-typescript produces by default).
  const pascal = kind
    .split("_")
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("");
  indexLines.push(`export type { ${pascal} } from "./${kind}";`);
}
const indexPath = resolve(outDir, "schemas.d.ts");
writeFileSync(indexPath, indexLines.join("\n") + "\n", "utf8");
console.log(`[gen:schemas]   wrote ${indexPath}`);

// Compatibility manifest: which kinds + which schema_versions the
// backend currently supports. The CLI consults this when emitting
// new files and when surfacing schema_version mismatches. No
// timestamp — git commit history is the provenance signal, and a
// per-run timestamp would defeat the drift check below.
const compatibility = {
  kinds: Object.fromEntries(
    kinds.map((k) => [k, { supported_versions: payload[k].schema_versions }]),
  ),
};
const compatPath = resolve(outDir, "compatibility.json");
writeFileSync(compatPath, JSON.stringify(compatibility, null, 2) + "\n", "utf8");
console.log(`[gen:schemas]   wrote ${compatPath}`);

console.log("[gen:schemas] done.");
