"""Render a project's synthesis artifacts as a single .docx readout."""

from __future__ import annotations

from io import BytesIO

from docx import Document
from docx.shared import Pt

from app.synthesis.exporters.common import (
    body_to_lines,
    category_label,
    group_by_category,
)
from app.synthesis.models import Artifact


def export_docx(project: dict, artifacts: list[Artifact]) -> bytes:
    """Return docx bytes containing every artifact, grouped by category."""
    doc = Document()

    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    customer = str(project.get("customer") or project.get("name") or "Customer").strip()
    project_name = str(project.get("name") or project.get("slug") or "Project").strip()

    doc.add_heading(f"{customer} — {project_name}", level=0)
    doc.add_paragraph("Synthesis readout generated by CORE Framework.").italic = True

    grouped = group_by_category(artifacts)
    for category, group in grouped.items():
        if not group:
            continue
        doc.add_heading(category_label(category), level=1)
        for artifact in group:
            doc.add_heading(artifact.title or artifact.type_id, level=2)
            if artifact.summary:
                doc.add_paragraph(artifact.summary)

            for label, value in body_to_lines(artifact.body):
                if not value:
                    continue
                doc.add_paragraph(label, style="Intense Quote")
                for line in value.splitlines():
                    line = line.strip()
                    if not line:
                        continue
                    if line.startswith("- "):
                        p = doc.add_paragraph(style="List Bullet")
                        p.add_run(line[2:].strip())
                    else:
                        doc.add_paragraph(line)

            if artifact.citations:
                doc.add_paragraph("Sources:", style="Intense Quote")
                for c in artifact.citations:
                    p = doc.add_paragraph(style="List Bullet")
                    p.add_run(c.source_id).bold = True
                    if c.quote:
                        p.add_run(f" — {c.quote[:220]}")

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()
